<?php

namespace AppBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticleTitle($title)
    {
        $queryBuilder = $this->createQueryBuilder('a');

        $query = $queryBuilder
            ->select('a')
            ->where('a.title=:title')
            ->setParameter('title', $title)
            ->getQuery();

        $results = $query->getArrayResult();

        return $results;


    }



    public function getArticleContent($content){

        //definition de la table dans laquelle on va chercher les infos
        $queryBuilder = $this->createQueryBuilder('a');
        //definition de la requete dans la table choisie
        $query = $queryBuilder
            ->select('a')
            ->where('a.content LIKE :content')
            ->orWhere('a.content LIKE :content')
            ->setParameter('content','%'.$content.'%')
            ->getQuery();
        //je récupere un array
        $results = $query->getArrayResult();

        return $results;
    }
}
