<?php

namespace AppBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductClearomiseursCategory($title)
    {
        $queryBuilder = $this->createQueryBuilder('ap');

        $query = $queryBuilder
            ->select('ap')
            ->where('ap.category=:category')
            ->setParameter('category', 'atomiseur')
            ->getQuery();

        $results = $query->getArrayResult();

        return $results;


    }

    public function getProductModsCategory($title)
    {
        $queryBuilder = $this->createQueryBuilder('ap');

        $query = $queryBuilder
            ->select('ap')
            ->where('ap.category=:category')
            ->setParameter('category', 'mods')
            ->getQuery();

        $results = $query->getArrayResult();

        return $results;


    }

    public function getProductAccessoriesCategory($title)
    {
        $queryBuilder = $this->createQueryBuilder('ap');

        $query = $queryBuilder
            ->select('ap')
            ->where('ap.category=:category')
            ->setParameter('category', 'accessoires')
            ->getQuery();

        $results = $query->getArrayResult();

        return $results;


    }

    
}
